import { BullionsTrader } from "@/lib/traderTypes";

export const seedTraders: BullionsTrader[] = [
  {
    id: "torion_desk",
    name: "Torion Desk",
    tag: "Verified MT5 challenger",
    avatar: "⚡",
    type: "REAL",
    status: "ACTIVE",
    verified: true,
    challengeTier: "TORION",
    challengeId: "torion_100k_s01",
    seasonId: "season_01",
    initialBalance: 100000,
    balance: 108420,
    equity: 109120,
    roi: 9.12,
    maxDrawdown: 3.4,
    winRate: 64,
    profitFactor: 2.18,
    consistency: 91,
    activity: 88,
    bullionsScore: 96.4,
    followers: 214,
    capitalFollowing: 428000,
    pair: "XAU/USD",
    style: "Low drawdown swing",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ghost_alpha",
    name: "Ghost Alpha",
    tag: "Risk-controlled scalper",
    avatar: "👻",
    type: "REAL",
    status: "ACTIVE",
    verified: true,
    challengeTier: "HELLION",
    challengeId: "hellion_50k_s01",
    seasonId: "season_01",
    initialBalance: 50000,
    balance: 53680,
    equity: 54120,
    roi: 8.24,
    maxDrawdown: 4.1,
    winRate: 59,
    profitFactor: 1.94,
    consistency: 87,
    activity: 93,
    bullionsScore: 92.7,
    followers: 156,
    capitalFollowing: 216000,
    pair: "BTC/USD",
    style: "Momentum scalping",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mia_capital",
    name: "Mia Capital",
    tag: "Index + gold specialist",
    avatar: "💎",
    type: "REAL",
    status: "ACTIVE",
    verified: true,
    challengeTier: "HELLION",
    challengeId: "hellion_50k_s01",
    seasonId: "season_01",
    initialBalance: 50000,
    balance: 52650,
    equity: 52980,
    roi: 5.96,
    maxDrawdown: 2.7,
    winRate: 67,
    profitFactor: 2.42,
    consistency: 94,
    activity: 76,
    bullionsScore: 91.8,
    followers: 98,
    capitalFollowing: 144000,
    pair: "US30",
    style: "Consistency first",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "bullions_ai",
    name: "Bullions AI",
    tag: "Adaptive allocation system",
    avatar: "☢️",
    type: "AI",
    status: "ACTIVE",
    verified: true,
    challengeTier: "URANIO",
    challengeId: "bullions_ai_core",
    seasonId: "season_01",
    initialBalance: 100000,
    balance: 112800,
    equity: 113400,
    roi: 13.4,
    maxDrawdown: 5.8,
    winRate: 61,
    profitFactor: 2.06,
    consistency: 89,
    activity: 99,
    bullionsScore: 95.2,
    followers: 412,
    capitalFollowing: 890000,
    pair: "MULTI",
    style: "AI diversified",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
